    <!-- Featured Products -->
    <section id="FeaturedProducts" class="min-h-screen flex flex-col justify-center items-center bg-[#1c1c1f] py-16">
        <div class="max-w-7xl mx-auto px-6 w-full">
            <h3 class="text-3xl font-semibold text-center mb-10 text-[#d4af37]">
                Featured Products
            </h3>
            <div id="productGrid" class="grid md:grid-cols-3 gap-8 mb-10">
                <!-- Product cards generated by JS -->
            </div>

            <!-- Pagination -->
            <div id="pagination" class="flex justify-center space-x-3 text-[#d4af37]"></div>
        </div>
    </section>
